name: build-and-release

on:
  push:
    # v* タグのみトリガー (例: v1.2.3)
    tags:
      - 'v*'
  # 手動実行は残す（必要な場合のみ）
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --ignore-scripts
      - run: npm run build:ci --all --openssl_fips=''

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prebuilds-Windows
          path: prebuilds
