name: Build iohook

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild (VS2019) to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '16'

      - name: Force VS2019 path to front of PATH
        run: |
          $vs2019 = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -version 16 -latest -property installationPath
          echo "VS2019 path: $vs2019"
          echo "$vs2019\MSBuild\Current\Bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Set msvs_version for node-gyp
        run: echo "msvs_version=2019" >> $env:GITHUB_ENV

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --ignore-scripts
      - run: npm run build:ci --all --openssl_fips=''

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows Prebuilds
          path: prebuilds

  build-mac:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      # Python3.12の影響でsetuptoolsが必要
      - name: install setuptools
        run: brew install python-setuptools
      - run: npm ci --ignore-scripts
      - run: npm run build:ci --all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macOS Prebuilds
          path: prebuilds

  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          sudo apt-get install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
          sudo apt-get update
      - name: Install dependencies (Ubuntu)
        run: sudo apt-get install libxtst-dev

      - run: npm ci --ignore-scripts
      - run: npm run build:ci --all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux (Ubuntu) Prebuilds
          path: prebuilds
